[theme]
base = "dark"
primaryColor = "#FF9900"
backgroundColor = "#16191F"
secondaryBackgroundColor = "#232F3E"
textColor = "#F2F3F3"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "info"

[server]
headless = true
runOnSave = true
enableXsrfProtection = true
enableCORS = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
